### ISSUE TITLE
Editor enrichment

### ISSUE THREAD

**Issue by DrSensor** [g-u-c/guc-desktop#32]
- [ ] support `@mention` ([zurb/tribute](https://github.com/zurb/tribute))
- [ ] Upload&Insert Image (#24)
- [ ] add&manages citations/references (I really need this :yum:)
- [ ] auto lookup previous notes (either published or unpublished)
